apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: date-printer
spec:
  selector:
    matchLabels:
      name: date-printer
  template:
    metadata:
      labels:
        name: date-printer
    spec:
      containers:
      - name: date-printer
        image: busybox:latest
        command: ["sh"]
        args: ["-c", "while true; do echo $(date); sleep 5; done;"]