apiVersion: apps/v1
kind: Deployment
metadata:
  name: canary-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      track: canary
  template:
    metadata:
      labels:
        track: canary
        app: customer-app
    spec:
      containers:
      - name: canary
        image: erwinjelly/ckad:canary
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: "50Mi"
            cpu: "50m"