apiVersion: v1
kind: Pod
metadata:
  name: nginx-custom
spec:
  volumes:
    - name: log-storage
      emptyDir: {}
    - name: nginx-storage
      persistentVolumeClaim:
        claimName: nginx-pvc
  containers:
  - image: nginx:alpine
    name: nginx-custom
    resources: {}
    ports:
    - containerPort: 80
    volumeMounts:
    - mountPath: /usr/share/nginx/html
      name: nginx-storage
    - mountPath: /var/log/nginx
      name: log-storage
