apiVersion: v1
kind: Pod
metadata:
  labels:
    run: multi-container-app
  name: multi-container-app
spec:
  volumes:
  - name: shared
    emptyDir: {}

  initContainers:
  - image: busybox:latest
    name: web
    command: ['sh', '-c', 'echo "App starting up..." > /shared/starting.log']
    volumeMounts:
    - name: shared
      mountPath: /shared

  - image: busybox:latest
    name: logger
    restartPolicy: Always
    command: ['sh', '-c', 'tail -n +1 -F /var/log/nginx/access.log']
    volumeMounts:
    - name: shared
      mountPath: /var/log/nginx

  containers:
  - image: nginx:alpine
    name: init
    ports:
    - containerPort: 80
    volumeMounts:
    - name: shared
      mountPath: /var/log/nginx